#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

start_service() {
    procd_open_instance
    # On lance le binaire qui est physiquement sur ta clé de 59 GiB
    procd_set_param command /opt/AdGuardHome/AdGuardHome -s run
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}
